version: '3'
services:
  db:
    container_name: mysql-app-db
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "4306:3306"